config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do



  authenticate :user, lambda { |user| user.is_admin? } do
    get 'reports' => 'reports#overall', as: 'reports'
    get 'reports/ymd'  => 'reports#ymd', as: 'report_ymd'
    get 'reports/received_week'  => 'reports#received_week', as: 'report_received_last_week'
    get 'members/:year/:month'  => 'members#index', as: 'members_month'
    get 'members/:year'  => 'members#index', as: 'members_year'
    resources :guests
    resources :members
    mount Blazer::Engine, at: "blazer"
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin
  end

  get '/home' => 'users#show', as: 'user_home'

  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end


  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  root 'pages#home'
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  validates :firstname, presence: true
  attachment :profile_image
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  load_and_authorize_resource :user
  respond_to :html, :json
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  def index
    @guests = Guest.all
    respond_with(@guests)
  end

  def show
    respond_with(@guest)
  end

  def new
    @guest = Guest.new
    respond_with(@guest)
  end

  def edit
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.save
    sponsor_id = Integer(guest_params.sponsor_name) rescue nil
    puts "***********"
    puts sponsor_id
    if sponsor_id.is_a? Numeric
      member = Member.find(sponsor_id)
      puts  member.firstname
      @guest.sponsor_name = member.firstname + ' ' + member.lastname
    end
    puts "***********"
    @guest.save
    respond_with(@guest)
  end

  def update
    @guest.update(guest_params)
    respond_with(@guest)
  end

  def destroy
    @guest.destroy
    respond_with(@guest)
  end

  private
    def set_guest
      @guest = Guest.find(params[:id])
    end

    def guest_params
      params.require(:guest).permit(:chapter, :division, :district, :profile_image, :profile_image_id, :profile_image_cache_id, :firstname, :lastname, :status, :last_meeting, :sponsor_name, :last_contact, :contact_person, :note)

    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/public_activity/guest/_create.html.haml
%li.list-group-item
  %span.glyphicon.glyphicon-edit
  %small.text-muted= a.created_at.strftime('%H:%M:%S %-d %B %Y')
  %br/
  %strong= activity.owner ? activity.owner.email : 'Guest'
  - if a.trackable
    create the guest #{link_to a.trackable.firstname, guest_path(a.trackable)}.
  - else
    create the guest that is currently deleted.

app/views/public_activity/guest/_destroy.html.haml
%li.list-group-item
  %span.glyphicon.glyphicon-remove
  %small.text-muted= a.created_at.strftime('%H:%M:%S %-d %B %Y')
  %br/
  %strong= activity.owner ? activity.owner.email : 'Guest'
  deleted a story.

app/views/public_activity/guest/_update.html.haml
%li.list-group-item
  %span.glyphicon.glyphicon-edit
  %small.text-muted= a.created_at.strftime('%H:%M:%S %-d %B %Y')
  %br/
  %strong= activity.owner ? activity.owner.email : 'Guest'
  - if a.trackable
    edited the guest #{link_to a.trackable.firstname, guest_path(a.trackable)}.
  - else
    edited the guest that is currently deleted.