config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do



  authenticate :user, lambda { |user| user.is_admin? } do
    get 'reports' => 'reports#overall', as: 'reports'
    get 'reports/ymd'  => 'reports#ymd', as: 'report_ymd'
    get 'reports/received_week'  => 'reports#received_week', as: 'report_received_last_week'
    get 'members/:year/:month'  => 'members#index', as: 'members_month'
    get 'members/:year'  => 'members#index', as: 'members_year'
    resources :guests
    resources :members
    mount Blazer::Engine, at: "blazer"
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin
  end

  get '/home' => 'users#show', as: 'user_home'

  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end


  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  root 'pages#home'
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  validates :firstname, presence: true
  attachment :profile_image
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  load_and_authorize_resource :user
  respond_to :html, :json
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  def index
    @guests = Guest.all
    respond_with(@guests)
  end

  def show
    respond_with(@guest)
  end

  def new
    @guest = Guest.new
    respond_with(@guest)
  end

  def edit
  end

  def create
    @guest = Guest.new(guest_params)
    @guest.save
    sponsor_id = Integer(guest_params.sponsor_name) rescue nil
    puts "***********"
    puts sponsor_id
    if sponsor_id.is_a? Numeric
      member = Member.find(sponsor_id)
      puts  member.firstname
      @guest.sponsor_name = member.firstname + ' ' + member.lastname
    end
    puts "***********"
    @guest.save
    respond_with(@guest)
  end

  def update
    @guest.update(guest_params)
    respond_with(@guest)
  end

  def destroy
    @guest.destroy
    respond_with(@guest)
  end

  private
    def set_guest
      @guest = Guest.find(params[:id])
    end

    def guest_params
      params.require(:guest).permit(:chapter, :division, :district, :profile_image, :profile_image_id, :profile_image_cache_id, :firstname, :lastname, :status, :last_meeting, :sponsor_name, :last_contact, :contact_person, :note)

    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.haml
- content_for :on_ready do
  $("#datepicker").DateTimePicker();

= simple_form_for(@guest) do |f|
  = f.error_notification


  .form-inputs
    .row
      .small-6.column
        = f.input :firstname, label: 'First Name'
      .small-6.column
        = f.input :lastname, label: 'Last Name'
    .row
      .small-6.column
        %label
          Division
          = f.select :division, options_for_select(division_status)
      .small-6.column
        = f.input :sponsor_name
    .row
      .small-6.column
        %label
          Chapter
          = f.select :chapter, options_for_select(harlem_chapters)
      .small-6.column
        %label
          Status
          = f.select :status, options_for_select(guest_status)
    .row
      .small-6.column.datepicker
        = f.input :last_meeting, as: :string, :input_html => { data: {field: "date"}}, value: Date.new
      .small-6.column.datepicker
        = f.input :last_contact, as: :string, :input_html => { data: {field: "date"}}, value: Date.new
    .row
      .small-12
        #datepicker

    .row
      .small-6.column
        %label
          Photo
          = f.attachment_field :profile_image
    .row
      .small-12.column
        = f.input :note

  .form-actions
    .row
      .small-12.column
        = f.button :submit, class: 'small-12 column even'

app/views/guests/edit.html.haml
%h1 Editing guest

= render 'form'

= link_to 'Show', @guest
\|
= link_to 'Back', guests_path

app/views/guests/index.html.haml
#index_list

  .row
    .small-12.medium-6.column
      = link_to 'New Guest', new_guest_path, class: 'button tiny'
    .small-12.medium-6.column.text-right
      %label{style: 'font-size: 18px;'}
        Search
        %input.fuzzy-search{:placeholder => "Search"}
    %br/
    %br/
  .row
    %table#index.medium-12.column
      %thead
        %tr
          %th{data: {  sort: "string"}}
            Firstname
          %th{data: {  sort: "string"}} Lastname
          %th{data: {  sort: "string"}} Division
          %th{data: {  sort: "string"}} Status
          %th{data: {  sort: "string"}} Sponsor name
          %th{data: {  sort: "int"}} Last contact
          %th
          %th
          %th

      %tbody.list
        - @guests.each do |guest|
          %tr
            %td.firstname= guest.firstname
            %td.lastname= guest.lastname
            %td.division= guest.division
            %td.status= guest.status
            %td.sponsor_name= guest.sponsor_name
            %td.last_contact= guest.last_contact
            %td= link_to 'Show', guest
            %td= link_to 'Edit', edit_guest_path(guest)
            %td= link_to 'Destroy', guest, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    = link_to 'New Guest', new_guest_path, class: 'button'

app/views/guests/new.html.haml
%h1 New guest

= render 'form'

= link_to 'Back', guests_path

app/views/guests/show.html.haml
%p#notice= notice


%p
  = image_tag attachment_url(@guest, :profile_image, :fill, 300, 300, format: "jpg")
%p
  %b Firstname:
  = @guest.firstname
%p
  %b Lastname:
  = @guest.lastname
%p
  %b Status:
  = @guest.status
%p
  %b Last meeting:
  = @guest.last_meeting
%p
  %b Sponsor name:
  = @guest.sponsor_name
%p
  %b Last contact:
  = @guest.last_contact
%p
  %b Contact person:
  = @guest.contact_person
%p
  %b Note:
  = @guest.note

= link_to 'Edit', edit_guest_path(@guest)
\|
= link_to 'Back', guests_path