config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do



  authenticate :user, lambda { |user| user.is_admin? } do
    get 'reports' => 'reports#overall', as: 'reports'
    get 'reports/ymd'  => 'reports#ymd', as: 'report_ymd'
    get 'reports/received_week'  => 'reports#received_week', as: 'report_received_last_week'
    get 'members/:year/:month'  => 'members#index', as: 'members_month'
    get 'members/:year'  => 'members#index', as: 'members_year'
    resources :guests
    resources :members
    mount Blazer::Engine, at: "blazer"
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin
  end

  get '/home' => 'users#show', as: 'user_home'

  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end


  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  root 'pages#home'
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  load_and_authorize_resource :user
  def ymd
  end

  def nearby

  end

  def received_week
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/overall.html.haml
.row
  .small-12.column
    .row
      .small-12.medium-6.column
        %h4 New Guests by Day
        = area_chart Guest.group_by_day(:created_at).count
      .small-12.medium-6.column
        %h4 New Members by Chapter
        = bar_chart Member.group(:chapter).count
    .row
      = link_to 'Deep dive', blazer_path, class: 'button large small-12 column'

app/views/reports/received_week.html.haml
%h1 Reports#received_week
%p Find me in app/views/reports/received_week.html.haml

app/views/reports/ymd.html.haml
%textarea#{:name => "", :cols => "30", :rows => "10"}
  = Member.where(date_received: 2015)