config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do



  authenticate :user, lambda { |user| user.is_admin? } do
    get 'reports' => 'reports#overall', as: 'reports'
    get 'reports/ymd'  => 'reports#ymd', as: 'report_ymd'
    get 'reports/received_week'  => 'reports#received_week', as: 'report_received_last_week'
    get 'members/:year/:month'  => 'members#index', as: 'members_month'
    get 'members/:year'  => 'members#index', as: 'members_year'
    resources :guests
    resources :members
    mount Blazer::Engine, at: "blazer"
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin
  end

  get '/home' => 'users#show', as: 'user_home'

  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end


  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  root 'pages#home'
end

app/models/member.rb
class Member < ActiveRecord::Base
  validates :firstname, presence: true
  attachment :photo
  # include PublicActivity::Model
  # tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }
  geocoded_by :entire_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource :user
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  def index
    if params.has_key?(:year)
      year = Date.new(params[:year].to_i)
      @members = Member.where("date_received >= ? AND date_received <= ?", year, year + 1.year - 1.day)
      if params.has_key?(:month)
        month = Date.new(params[:year], param[:month].to_i)
        @members = Member.where("date_received >= ? AND date_received <= ?", month, month + 1.month - 1.day)
      end
    else
      @members = Member.all
    end
    respond_with(@members)
  end

  def show
    respond_with(@member)
  end

  def new
    @member = Member.new
    respond_with(@member)
  end

  def edit
  end

  def create
    @member = Member.new(member_params)
    @member.save
    respond_with(@member)
  end

  def update
    @member.update(member_params)
    respond_with(@member)
  end

  def destroy
    @member.destroy
    respond_with(@member)
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:territory, :member_uid, :email, :phone_primary, :phone_secondary, :address, :state, :zipcode, :subscription, :auto_renewal, :sustaining_contributor, :photo, :photo_id, :firstname, :lastname, :division, :date_received, :zone, :region, :chapter, :district, :sponsor_name, :enshrined, :district_connected, :contact_person, :note)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
- content_for :on_ready do
  $("#datepicker").DateTimePicker();

= simple_form_for(@member) do |f|
  = f.error_notification

  .form-inputs
    .row
      .small-6.column
        = f.input :firstname, required: true
      .small-6.column
        = f.input :lastname, required: true
    .row
      .small-6.column
        %label
          Division
          = f.select :division, options_for_select(division_status)
    .row
      .small-6.column
        = f.input :chapter,
          :collection =>  harlem_chapters
      .small-6.column
        = f.input :district,
          :as => :grouped_select,
          :collection =>  harlem_district_array,
          :group_method => :last,
          class: 'district-selector'
    .row
      .small-6.column.datepicker
        = f.input :date_received, as: :string, :input_html => { data: {field: "date"}}, value: Date.new
      .small-6.column
        = f.input :sponsor_name,
          :collection =>  [],
          :group_method => :last
    .row
      .small-12
        #datepicker
    .row
      .small-12.column
        %label
          Photo
          = f.attachment_field :photo
    .row
      .small-12.column
        = f.input :note
    .row
      .small-6.column
        = f.input :contact_person,
          :collection =>  [],
          :group_method => :last

      .small-6.column
        = f.input :last_contact, as: :string, :input_html => { data: {field: "date"}}, value: Date.new
    .row
      .small-4.column
        = f.input :enshrined, label: "Enshrined"
      .small-4.column
        = f.input :district_connected, label: "Connected to district"
  .form-actions
    .row
      .small-12.column
        = f.button :submit

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
#index_list
  %h1 Listing members

  .row
    .small-12.medium-6.column
      = link_to 'New Member', new_member_path, class: 'button tiny'
    .small-12.medium-6.column.text-right
      %label{style: 'font-size: 18px;'}
        Search
        %input.fuzzy-search{:placeholder => "Search"}
  %table#index.medium-12.column
    %tr
      %th{data: {  sort: "string"}} Firstname
      %th{data: {  sort: "string"}} Lastname
      %th{data: {  sort: "int"}} Date received
      %th{data: {  sort: "string"}} Chapter
      %th{data: {  sort: "string"}} District
      %th
      %th
      %th

    %tbody.list
      - @members.each do |member|
        %tr
          %td.firstname= member.firstname
          %td.lastname= member.lastname
          %td.date_received= member.date_received
          %td.chapter= member.chapter
          %td.district= member.district
          %td= link_to 'Show', member
          %td= link_to 'Edit', edit_member_path(member)
          %td= link_to 'Destroy', member, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'New Member', new_member_path, class: 'button'

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice

%p
  = image_tag attachment_url(@member, :photo_id, :fill, 300, 300, format: "jpg")
%p
  %b Firstname:
  = @member.firstname
%p
  %b Lastname:
  = @member.lastname
%p
  %b Date received:
  = @member.date_received
%p
  %b Zone:
  = @member.zone
%p
  %b Region:
  = @member.region
%p
  %b Chapter:
  = @member.chapter
%p
  %b District:
  = @member.district
%p
  %b Sponsor name:
  = @member.sponsor_name
%p
  %b Enshrined:
  = @member.enshrined
%p
  %b District connected:
  = @member.district_connected
%p
  %b Contact person:
  = @member.contact_person
%p
  %b Note:
  = @member.note

= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path